---
title: "PGS_Analysis"
author: "Peter Fiorica"
date: "`r Sys.Date()`"
output: html_document
---


```{r dependencies_and_functions, warning = FALSE, message=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(viridis))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(UpSetR))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(ggsci))
suppressPackageStartupMessages(library(patchwork))
"%&%"=function(a,b) paste(a,b,sep="")

map_race <- function(race_abbr) {
  case_when(
    race_abbr == "p_white" ~ "White",
    race_abbr == "p_black" ~ "Black",
    race_abbr == "p_asian" ~ "Asian",
    race_abbr == "p_hispanic" ~ "Hispanic",
    race_abbr == "p_overall" ~ "Overall",
    TRUE ~ race_abbr  # Return the original abbreviation if it doesn't match any of the above
  )
}

cvd.dir <-"C://Users/pe42518/OneDrive - University at Buffalo/Documents/Ambrosone_Yao/30_PGS_CVD_CMD/"
```


```{r input, warning=FALSE}
pgs_compare<-fread(cvd.dir %&%"CAD_PGS_Comparison_working.csv")
# Result Data
az_results<-readRDS(cvd.dir %&% "A_Zimbalist_Results_2_22_2024/all_results_norounding.rds")

#Outcome naming document
outcome_rename<-fread(cvd.dir %&%"survival_outcome_rename.csv", header = T)
```

```{r, manipulate_format}
az_results_edit1 <- az_results %>% 
  mutate(term=str_remove(term, "z_pgs_")) %>%
  left_join(outcome_rename, by = c("outcome"="AZ_Names")) %>%
  select(-outcome, -Old_Names)%>%
  rename(Trait=term)%>%
  mutate(Trait_for_merge=  tolower(gsub("[[:punct:]]", "", Trait))) %>%  
  #Overall
  separate(`hr_overall`, " ", into = c("HR_Overall", "95%_CI_Overall")) %>%
  mutate(HR_Overall = as.numeric(HR_Overall)) %>%
  mutate(`95%_CI_Overall` = str_remove_all(`95%_CI_Overall`, "[()]")) %>% 
  separate(`95%_CI_Overall`, ",", into = c("lower_CI", "upper_CI")) %>%
  mutate(lower_CI = as.numeric(lower_CI)) %>%
  mutate(upper_CI = as.numeric(upper_CI)) %>%
  # White
  separate(`hr_white`, " ", into = c("HR_WHITE", "95%_CI_WHITE")) %>%
  mutate(HR_WHITE = as.numeric(HR_WHITE)) %>%
  mutate(`95%_CI_WHITE` = str_remove_all(`95%_CI_WHITE`, "[()]")) %>%
  separate(`95%_CI_WHITE`, ",", into = c("lower_CI_WHITE", "upper_CI_WHITE")) %>% 
  mutate(lower_CI_WHITE = as.numeric(lower_CI_WHITE)) %>%
  mutate(upper_CI_WHITE = as.numeric(upper_CI_WHITE)) %>%
  # Black
  separate(`hr_black`, " ", into = c("HR_BLACK", "95%_CI_BLACK")) %>%
  mutate(HR_BLACK = as.numeric(HR_BLACK)) %>%
  mutate(`95%_CI_BLACK` = str_remove_all(`95%_CI_BLACK`, "[()]")) %>%
  separate(`95%_CI_BLACK`, ",", into = c("lower_CI_BLACK", "upper_CI_BLACK")) %>% 
  mutate(lower_CI_BLACK = as.numeric(lower_CI_BLACK)) %>%
  mutate(upper_CI_BLACK = as.numeric(upper_CI_BLACK)) %>%
  # Hispanic
  separate(`hr_hispanic`, " ", into = c("HR_HISPANIC", "95%_CI_HISPANIC")) %>%
  mutate(HR_HISPANIC = as.numeric(HR_HISPANIC)) %>%
  mutate(`95%_CI_HISPANIC` = str_remove_all(`95%_CI_HISPANIC`, "[()]")) %>%
  separate(`95%_CI_HISPANIC`, ",", into = c("lower_CI_HISPANIC", "upper_CI_HISPANIC")) %>% 
  mutate(lower_CI_HISPANIC = as.numeric(lower_CI_HISPANIC)) %>%
  mutate(upper_CI_HISPANIC = as.numeric(upper_CI_HISPANIC)) %>%
  # Asian
  separate(`hr_asian`, " ", into = c("HR_ASIAN", "95%_CI_ASIAN")) %>%
  mutate(HR_ASIAN = as.numeric(HR_ASIAN)) %>%
  mutate(`95%_CI_ASIAN` = str_remove_all(`95%_CI_ASIAN`, "[()]")) %>%
  separate(`95%_CI_ASIAN`, ",", into = c("lower_CI_ASIAN", "upper_CI_ASIAN")) %>% 
  mutate(lower_CI_ASIAN = as.numeric(lower_CI_ASIAN)) %>%
  mutate(upper_CI_ASIAN = as.numeric(upper_CI_ASIAN)) 

# Update Trait Names
az_results_edit2 <- az_results_edit1   %>%
  mutate(Trait = str_to_title(str_replace_all(Trait, "_", " ")))


#Traits to remove
traits2remove<-c("Cad3725", # 4 outdated CAD PGS
                 "Cad3",
                 "Cardiovascular Disease",
                 "Coronary Heart Disease",
                 "Type 2 Diabetes", # Out-dated t2d PGS
                 "Systolic Blood Pressure" #SBP is the non multi-ethnic model
                 )

az_results_edit <- az_results_edit2 %>%
  filter(!Trait %in% traits2remove) %>%
  rename(`CMD/CVD Outcome`=New_Names) %>%
  filter(`CMD/CVD Outcome`!= "All cause death") %>%
  mutate(Trait = str_replace_all(Trait, "Sbp", "Systolic Blood Pressure")) %>%
  mutate(Trait = str_replace_all(Trait, "Cad2", "Coronary Artery Disease")) %>%
  mutate(Trait = str_replace_all(Trait, "Diabetes", "Type 2 Diabetes")) %>%
  mutate(Trait = str_replace_all(Trait, "Hdl", "HDL")) %>%
  mutate(Trait = str_replace_all(Trait, "Ldl", "LDL")) %>%
  mutate(Trait = str_replace_all(Trait, "Bmi", "BMI"))


az_results_for_plot<- az_results_edit %>%
  mutate(CMD_or_CVD= if_else(`CMD/CVD Outcome` %in% c("Diabetes", "Dyslipidemia", "Hypertension", "Any CMD"), "Cardiometabolic risk factors", "Cardiovascular disease events"))
```

# Figure 1

```{r}

desired_order <- c("Any CMD", "Diabetes", "Dyslipidemia", "Hypertension", "Any CVD", "Serious CVD", "Arrhythmia", "HF or cardiomyopathy", 
                   "Ischemic heart disease", "Stroke", "VTE", "CVD-related death")

az_results_for_plot$`CMD/CVD Outcome` <- factor(az_results_for_plot$`CMD/CVD Outcome`, levels = desired_order)

az_results_for_plot <- az_results_for_plot %>%
  mutate(Facet_Group = if_else(`CMD/CVD Outcome` %in% c("Any CMD", "Hypertension", "Diabetes", "Dyslipidemia"), "Cardiometabolic risk factors", "Cardiovascular disease events"))


#WHITE P-VALUE PLOT
ggplot(az_results_for_plot, aes(x = `CMD/CVD Outcome`, y = -log10(p_white), fill = `CMD/CVD Outcome`)) +
  geom_point(shape = 21, aes(size = ifelse(-log10(p_white) > -log10(0.05 / nrow(az_results_for_plot)), HR_WHITE, 1)), 
             position = position_jitter(width = 0.25), alpha = 0.5) +
  geom_hline(yintercept = -log10((0.05 / nrow(az_results_for_plot))), color = "red", alpha = 0.5) +
  scale_size_continuous(name = "HR", 
                        breaks = c(1, 1.1, 1.2, 1.3, 1.4, 1.5),
                        range = c(1, 10),
                        labels = c("1", "1.1", "1.2", "1.3", "1.4", "1.5")) +
  geom_text_repel(size = 3,
    data = subset(az_results_for_plot, -log10(p_white) > -log10(0.05 / nrow(az_results_for_plot))),
    aes(label = Trait),
    box.padding = 0.25,
    point.padding = 0.25,
    segment.color = "grey50",
    max.overlaps = Inf  # Set to a large value or Inf to allow more overlaps
  ) +
  ylab(expression(-log[10](P))) +
  scale_fill_npg() +
  guides(fill = "none") +
  facet_wrap(~ Facet_Group, ncol = 2, scales = "free_x") +
  theme_bw(16) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
```

# Figure 2

Provided by Alexa Zimbalist.

# Supplemental Table 2

```{r}
white_trans_sig<- az_results_for_plot %>% filter(p_white<(0.05/nrow(az_results_for_plot)))

overall <- white_trans_sig %>% select( `CMD/CVD Outcome`,  Trait, HR=HR_Overall, lower_CI, upper_CI, P=p_overall) %>%
  mutate(Ethnicity="Overall")
white <- white_trans_sig %>% select( `CMD/CVD Outcome`,  Trait, HR=HR_WHITE, lower_CI=lower_CI_WHITE, upper_CI=upper_CI_WHITE, P=p_white)%>%
  mutate(Ethnicity="White")
black <- white_trans_sig %>% select( `CMD/CVD Outcome`,  Trait,HR= HR_BLACK, lower_CI=lower_CI_BLACK, upper_CI=upper_CI_BLACK, P=p_black)%>%
  mutate(Ethnicity="Black")
hispanic <- white_trans_sig %>% select( `CMD/CVD Outcome`,  Trait, HR= HR_HISPANIC, lower_CI=lower_CI_HISPANIC, upper_CI=upper_CI_HISPANIC, P=p_hispanic) %>%
  mutate(Ethnicity="Hispanic")
asian <- white_trans_sig %>% select( `CMD/CVD Outcome`,  Trait, HR=HR_ASIAN, lower_CI=lower_CI_ASIAN, upper_CI=upper_CI_ASIAN, P=p_asian) %>%
  mutate(Ethnicity="Asian")
new_trans_sig<- bind_rows(overall, white,black, hispanic,asian)
# This is a brute force method that I need to figure out how to automate it. I imagine dyplyr or tidyr has a better way to do this...

# Create a new column to specify the point shapes
new_trans_sig$Shape <- ifelse(new_trans_sig$Ethnicity == "Overall", "Overall", "Others")
# Convert the Shape column to a factor with specific levels and labels
new_trans_sig$Shape <- factor(new_trans_sig$Shape, levels = c("Others", "Overall"), labels = c(21, 23))
ethnicity_order <- c("Overall", "White", "Hispanic", "Black", "Asian")

# Convert SIRE to a factor with the custom order
new_trans_sig$Ethnicity <- factor(new_trans_sig$Ethnicity, levels = ethnicity_order)

white_trans_sig <- white_trans_sig %>% select(-Trait_for_merge) %>%
  select(`CMD/CVD Outcome`, everything()) %>%
  mutate(p_overall=format(p_overall, scientific = TRUE, digits = 3)) %>%
  mutate(p_white=format(p_white, scientific = TRUE, digits = 3)) %>%
  mutate(p_black=format(p_black, scientific = TRUE, digits = 3)) %>%
  mutate(p_asian=format(p_asian, scientific = TRUE, digits = 3)) %>%
  mutate(p_hispanic=format(p_hispanic, scientific = TRUE, digits = 3))


white_trans_sig2write <- white_trans_sig %>%
  mutate(`Overall HR (95% CI)` = paste0(HR_Overall," (", lower_CI, ", ", upper_CI, ")")) %>%
  mutate(`White HR (95% CI)` = paste0(HR_WHITE," (", lower_CI_WHITE, ", ", upper_CI_WHITE, ")")) %>%
  mutate(`Black HR (95% CI)` = paste0(HR_BLACK," (", lower_CI_BLACK, ", ", upper_CI_BLACK, ")")) %>%
  mutate(`Asian HR (95% CI)` = paste0(HR_ASIAN," (", lower_CI_ASIAN, ", ", upper_CI_ASIAN, ")")) %>%
  mutate(`Hispanic HR (95% CI)` = paste0(HR_HISPANIC," (", lower_CI_HISPANIC, ", ", upper_CI_HISPANIC, ")")) %>%
  select(`CMD/CVD Outcome`, Trait, `Overall HR (95% CI)`, `P-Value (Overall)`= p_overall, `White HR (95% CI)`, `P-Value (White)`=  p_white, `Black HR (95% CI)`, `P-Value (Black)`=  p_black, `Asian HR (95% CI)`, `P-Value (Asian)`=  p_asian, `Hispanic HR (95% CI)`, `P-Value (Hispanic)`=  p_asian) 

#fwrite(white_trans_sig2write, cvd.dir %&% "Supplental Table 2.csv", quote = T, sep = ",", row.names = F, col.names = T)
```

# Supplemental Table 3

Sourced from PGS Catalog


# Figure 3

```{r, fig.width=12, fig.height=8}
p_1 <- new_trans_sig %>%
  filter(`CMD/CVD Outcome` %in% (c("Any CMD", "Dyslipidemia", "Diabetes", "Hypertension"))) %>%
  ggplot(aes(x = Trait, y = HR, ymin = lower_CI, ymax = upper_CI, fill = `CMD/CVD Outcome`, shape = Shape)) +
  geom_pointrange(position = position_dodge2(0.8)) + 
  geom_hline(yintercept = 1, lty = 2) + 
  geom_text(size = 2.5, position=position_dodge2(0.8),aes(y = 0.25, label = Ethnicity),  # Set x to 0.5 for fixed position
            hjust = 0.5,  # Center the labels horizontally
            show.legend = FALSE)+ ylim(c(0,3))+
  coord_flip() +
  scale_fill_npg() +
  scale_shape_manual(values = c(21, 23)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  facet_wrap(~ paste(`CMD/CVD Outcome`), ncol = 2, scales = "free_y") +
  theme_bw(14) + theme(legend.position = "none")

p_1
```

# Figure 4

```{r}
p_2 <- new_trans_sig %>%
  filter(`CMD/CVD Outcome` %in% (c("Any CVD", "Arrhythmia", "Ischemic heart disease", "Serious CVD"))) %>%
  ggplot(aes(x = Trait, y = HR, ymin = lower_CI, ymax = upper_CI, fill = `CMD/CVD Outcome`, shape = Shape)) +
  geom_pointrange(position = position_dodge2(0.8)) + 
  geom_hline(yintercept = 1, lty = 2) + 
  geom_text(size = 2.5, position=position_dodge2(0.8),aes(y = 0.25, label = Ethnicity),  # Set x to 0.5 for fixed position
            hjust = 0.5,  # Center the labels horizontally
            show.legend = FALSE)+ ylim(c(0,4))+
  coord_flip() +
  scale_fill_npg() +
  scale_shape_manual(values = c(21, 23)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  facet_wrap(~ paste(`CMD/CVD Outcome`), ncol = 1, scales = "free_y") +
  theme_bw(14) + theme(legend.position = "none")

p_2
```

# Supplemental Table 1

PGS Information: Sourced from PGS Catalog.


# Supplemental Figure 1

```{r}
#OVERALL P-VALUE PLOT
ggplot(az_results_for_plot, aes(x = `CMD/CVD Outcome`, y = -log10(p_overall), fill = `CMD/CVD Outcome`)) +
  geom_point(shape = 21, aes(size = ifelse(-log10(p_overall) > -log10(0.05 / nrow(az_results_for_plot)), HR_Overall, 1)), 
             position = position_jitter(width = 0.25), alpha = 0.5) +
  geom_hline(yintercept = -log10((0.05 / nrow(az_results_for_plot))), color = "red", alpha = 0.5) +
  scale_size_continuous(name = "HR (Overall)", 
                        breaks = c(1, 1.1, 1.2, 1.3, 1.4, 1.5),
                        range = c(1, 10),
                        labels = c("1", "1.1", "1.2", "1.3", "1.4", "1.5")) +
  geom_text_repel(size = 3,
    data = subset(az_results_for_plot, -log10(p_overall) > -log10(0.05 / nrow(az_results_for_plot))),
    aes(label = Trait),
    box.padding = 0.25,
    point.padding = 0.25,
    segment.color = "grey50",
    max.overlaps = Inf  # Set to a large value or Inf to allow more overlaps
  ) +
  ylab(expression(-log[10](P))) +
  scale_fill_npg() +
  guides(fill = "none") +
  facet_wrap(~ Facet_Group, ncol = 2, scales = "free_x") +
  theme_bw(12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
```

# Supplemental Figure 2

```{r, fig.width=10}
total_tran_sig<-az_results_for_plot %>% filter(p_overall<(0.05/nrow(az_results_for_plot))) %>%
  select(-Trait_for_merge) %>%
  select(`CMD/CVD Outcome`, everything()) %>%
  mutate(p_overall=format(p_overall, scientific = TRUE, digits = 3)) %>%
  mutate(p_white=format(p_white, scientific = TRUE, digits = 3)) %>%
  mutate(p_black=format(p_black, scientific = TRUE, digits = 3)) %>%
  mutate(p_asian=format(p_asian, scientific = TRUE, digits = 3)) %>%
  mutate(p_hispanic=format(p_hispanic, scientific = TRUE, digits = 3))

ovr_sig <-  setdiff(total_tran_sig, white_trans_sig)


total_trans_sig2write <- ovr_sig %>%
  mutate(`Overall HR (95% CI)` = paste0(HR_Overall," (", lower_CI, ", ", upper_CI, ")")) %>%
  mutate(`White HR (95% CI)` = paste0(HR_WHITE," (", lower_CI_WHITE, ", ", upper_CI_WHITE, ")")) %>%
  mutate(`Black HR (95% CI)` = paste0(HR_BLACK," (", lower_CI_BLACK, ", ", upper_CI_BLACK, ")")) %>%
  mutate(`Asian HR (95% CI)` = paste0(HR_ASIAN," (", lower_CI_ASIAN, ", ", upper_CI_ASIAN, ")")) %>%
  mutate(`Hispanic HR (95% CI)` = paste0(HR_HISPANIC," (", lower_CI_HISPANIC, ", ", upper_CI_HISPANIC, ")")) %>%
  select(`CMD/CVD Outcome`, Trait, `Overall HR (95% CI)`, `P-Value (Overall)`= p_overall, `White HR (95% CI)`, `P-Value (White)`=  p_white, `Black HR (95% CI)`, `P-Value (Black)`=  p_black, `Asian HR (95% CI)`, `P-Value (Asian)`=  p_asian, `Hispanic HR (95% CI)`, `P-Value (Hispanic)`=  p_asian) 

overall <- ovr_sig %>% select( `CMD/CVD Outcome`,  Trait, HR=HR_Overall, lower_CI, upper_CI, P=p_overall) %>%
  mutate(Ethnicity="Overall")
white <- ovr_sig %>% select( `CMD/CVD Outcome`,  Trait, HR=HR_WHITE, lower_CI=lower_CI_WHITE, upper_CI=upper_CI_WHITE, P=p_white)%>%
  mutate(Ethnicity="White")
black <- ovr_sig %>% select( `CMD/CVD Outcome`,  Trait,HR= HR_BLACK, lower_CI=lower_CI_BLACK, upper_CI=upper_CI_BLACK, P=p_black)%>%
  mutate(Ethnicity="Black")
hispanic <- ovr_sig %>% select( `CMD/CVD Outcome`,  Trait, HR= HR_HISPANIC, lower_CI=lower_CI_HISPANIC, upper_CI=upper_CI_HISPANIC, P=p_hispanic) %>%
  mutate(Ethnicity="Hispanic")
asian <- ovr_sig %>% select( `CMD/CVD Outcome`,  Trait, HR=HR_ASIAN, lower_CI=lower_CI_ASIAN, upper_CI=upper_CI_ASIAN, P=p_asian) %>%
  mutate(Ethnicity="Asian")
new_total_trans_sig<- bind_rows(overall, white,black, hispanic,asian)

# Create a new column to specify the point shapes
new_total_trans_sig$Shape <- ifelse(new_total_trans_sig$Ethnicity == "Overall", "Overall", "Others")
# Convert the Shape column to a factor with specific levels and labels
new_total_trans_sig$Shape <- factor(new_total_trans_sig$Shape, levels = c("Others", "Overall"), labels = c(21, 23))
ethnicity_order <- c("Overall", "White", "Hispanic", "Black", "Asian")

# Convert Ethnicity to a factor with the custom order
new_total_trans_sig$Ethnicity <- factor(new_total_trans_sig$Ethnicity, levels = ethnicity_order)

new_total_trans_sig %>%
  #filter(`CMD/CVD Outcome` %in% (c("Any CMD", "Dyslipidemia", "Diabetes", "Hypertension"))) %>%
  ggplot(aes(x = Trait, y = HR, ymin = lower_CI, ymax = upper_CI, fill = `CMD/CVD Outcome`, shape = Shape)) +
  geom_pointrange(position = position_dodge2(0.8)) + 
  geom_hline(yintercept = 1, lty = 2) + 
  geom_text(size = 2.5, position=position_dodge2(0.8),aes(y = 0.25, label = Ethnicity),  # Set x to 0.5 for fixed position
            hjust = 0.5,  # Center the labels horizontally
            show.legend = FALSE)+ ylim(c(0,4))+
  coord_flip() +
  scale_fill_npg() +
  scale_shape_manual(values = c(21, 23)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  facet_wrap(~ paste(`CMD/CVD Outcome`), ncol = 2, scales = "free_y") +
  theme_bw(14) + theme(legend.position = "none")
```

# Supplemental Figure 3

```{r}
pgs2compare<-c(traits2remove, "Diabetes", "Cad2", "Sbp")
for_comparison <- az_results_edit2%>% filter(Trait %in% pgs2compare)%>%
  mutate(Training_Source=if_else(Trait %in% c(traits2remove), "Euro-centric", "Multi-Ethnic"))

htn<-for_comparison %>%
  filter(New_Names == "Hypertension") %>%
  filter(Trait %in% c("Sbp", "Systolic Blood Pressure"))

t2d<-for_comparison %>% 
  filter(New_Names == "Diabetes") %>%
  filter(Trait %in% c("Type 2 Diabetes","Diabetes"))

cad <- for_comparison %>%
  filter(New_Names =="Ischemic heart disease") %>%
  filter(Trait %in% c("Cad2", "Cad3", "Cad3725", "Coronary Heart Disease"))

multi_3<- bind_rows(htn, t2d, cad)

# Convert HR and p-values to binary format
binary_data <- multi_3 %>%
  select(starts_with("p_")) %>%
  mutate_all(~ if_else(. < 0.05, 1, 0)) %>%
  mutate(row_sum = rowSums(select(., starts_with("p_"))))

# Add New_Names column to binary data
binary_data$New_Names <- multi_3$New_Names
binary_data$Trait <- multi_3$Trait
binary_data <- binary_data %>%
  mutate(Trait = factor(Trait, levels = unique(.$Trait[order(.$New_Names)])))

# Pivot longer and replace race abbreviations with their full names
binary_data_long <- binary_data %>%
  pivot_longer(cols = starts_with("p_"), names_to = "SIRE", values_to = "Significance") %>%
  filter(Significance == 1) %>%
  mutate(SIRE = map_race(SIRE)) %>% 
  rename(`CMD/CVD Events`=New_Names ) %>%
  mutate(`CMD/CVD Events`= str_to_title(`CMD/CVD Events`)) 

# Convert SIRE to factor with custom levels
binary_data_long$SIRE <- factor(binary_data_long$SIRE,
                                levels = rev(c("Overall", "Asian", "Black", "Hispanic", "White")))

pgs_compare<- pgs_compare %>% mutate(Working_Name=str_to_title(Working_Name))

binary_data_long <- left_join(binary_data_long, pgs_compare, by = c("Trait"="Working_Name")) 
binary_data_long$Labeled_Name <- gsub("etes \\(PG", "etes\n(PG" ,binary_data_long$Labeled_Name)
binary_data_long$Labeled_Name <- gsub("sure \\(PG", "sure\n(PG" ,binary_data_long$Labeled_Name)

dots<- ggplot(binary_data_long, aes(x = Labeled_Name, y = SIRE, fill = `CMD/CVD Events`)) +
  geom_point(shape = 21, size = 4) +
  labs(x = "PGS", y = NULL) +
  scale_fill_npg() + theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + facet_grid(~`CMD/CVD Events`, scales = "free_x") + 
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none")

colnames(multi_3) <- str_to_lower(colnames(multi_3))

df_long <- multi_3 %>%
  rename(lower_ci_overall = lower_ci) %>%
  rename(upper_ci_overall = upper_ci) %>%
  pivot_longer(cols = starts_with(c("hr_", "lower_ci_", "upper_ci_", "p_")), 
               names_to = c(".value", "SIRE"), 
               names_pattern = "(hr_|lower_ci_|upper_ci_|p_)(.*)") %>%
  select(-trait_for_merge) %>%
  mutate(SIRE = str_to_title(SIRE)) %>%
  mutate(new_names= str_to_title(new_names)) %>%
  rename(`CMD/CVD Events`=new_names)

jitter<- ggplot(df_long, aes(y = -log10(p_), x= trait, color= `CMD/CVD Events` , shape = SIRE))+
  geom_point(alpha = 0.75, size =4, position = position_jitter(width = 0.25))+
  facet_grid(~`CMD/CVD Events`, scales = "free_x")+
  scale_color_npg() +
  theme_bw()+
  ylab(expression(-log[10](P))) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(color = FALSE)

leg<- cowplot::get_legend(jitter)


jitter<-jitter+ theme(legend.position = "none")+ theme(axis.text.x = element_blank()) +  # Remove x-axis labels
  theme(axis.title.x = element_blank())
#grid.arrange(grobs= list(jitter, dots), ncol=1, heights=c(1.5,1))

gA <- ggplotGrob(jitter)
gB <- ggplotGrob(dots)
maxWidth = grid::unit.pmax(gA$widths[2:5], gB$widths[2:5])
gA$widths[2:5] <- as.list(maxWidth)
gB$widths[2:5] <- as.list(maxWidth)
a1<-grid.arrange(gA, gB, ncol=1, heights=c(1.5,.85))
grid.arrange(a1, leg, widths=c(1.25, 0.45))
```


# Figure 5

```{r}
sire_sums <- binary_data %>%
  summarise(Asian = sum(p_asian),
            Black = sum(p_black),
            Hispanic = sum(p_hispanic),
            White = sum(p_white),
            Overall = sum(p_overall))
# Convert sire_sums to long format for easier plotting
sire_sums_long <- sire_sums %>%
  pivot_longer(cols = -Overall, names_to = "Group", values_to = "Count")
# Create a new row for Overall data
overall_row <- tibble(Group = "Overall", Count = sire_sums$Overall)
sire_sums_long <- bind_rows(sire_sums_long, overall_row)
sire_sums_long$Group <- factor(sire_sums_long$Group,
                               levels = rev(c("Overall", "Asian", "Black", "Hispanic", "White")))

#HORIZONTAL BARS
horz_bars<- ggplot(sire_sums_long, aes(x = -(Count), y = Group)) +
  geom_col() +
  labs(title = NULL,
       x = NULL,  # Remove x-axis title
       y = NULL) +
  scale_x_continuous(name = "Count",
                     breaks = seq( 0,-10, by = -2),
                     labels = seq( 0,10, by =  2)) +
  theme_minimal()+
  theme(legend.position = "none") + theme(plot.margin = margin(0, 0, 0, 0, "cm"))


dot_plot_data<- bind_rows(white_trans_sig,ovr_sig) %>%
  select(`CMD/CVD Outcome`, Trait, starts_with("HR_"), starts_with("p_")) %>%
  pivot_longer(cols = starts_with("HR_"), names_to = "Race_Ethnicity", values_to = "HR") %>%
  pivot_longer(cols = starts_with("p_"), names_to = "Race_Ethnicity_P", values_to = "p_value") %>%
  mutate(Race_Ethnicity = gsub("HR_", "", Race_Ethnicity),
         Race_Ethnicity_P = gsub("p_", "", Race_Ethnicity_P))%>%
  filter(tolower(Race_Ethnicity) == tolower(Race_Ethnicity_P)) %>%
  mutate(Race_Ethnicity = str_to_title(Race_Ethnicity))

dot_plot_data$p_value <- as.numeric(dot_plot_data$p_value)

to_replace<-c("Any CVD", "Serious CVD", "Ischemic heart disease")
replace_dict<-c("Any\nCVD", "Serious\nCVD", "Ischemic\nheart disease")
#replacement_vector <- setNames(replace_dict, to_replace)

dot_plot_data <- dot_plot_data %>%
  mutate(`CMD/CVD Outcome` = gsub(to_replace[1], replace_dict[1], `CMD/CVD Outcome`))%>%
  mutate(`CMD/CVD Outcome` = gsub(to_replace[2], replace_dict[2], `CMD/CVD Outcome`))%>%
  mutate(`CMD/CVD Outcome` = gsub(to_replace[3], replace_dict[3], `CMD/CVD Outcome`)) %>%
  rename(SIRE=Race_Ethnicity)

dot_plot_data$`CMD/CVD Outcome` <- factor(dot_plot_data$`CMD/CVD Outcome`, levels = c("Any CMD","Hypertension","Diabetes","Dyslipidemia", "Any\nCVD" , "Serious\nCVD"  ,"Arrhythmia"              ,"Ischemic\nheart disease"))
dot_plot_data$SIRE <- factor(dot_plot_data$SIRE, levels = c("Asian", "Black", "Hispanic", "White", "Overall"))

dot_plot<- ggplot(dot_plot_data, aes(x=SIRE, y = Trait,
                                     #size = -log10(p_value),
                                     fill = HR))+
  geom_point(shape = 21, size = 6.5)+
  scale_fill_gradient2(low = "#4DBBD5FF" ,high = "#E64B35FF", mid="white", midpoint = 1.00)+
  facet_grid(`CMD/CVD Outcome` ~ ., scales = "free_y", space = "free_y")+
  theme_bw(12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels
        strip.text.y = element_text(size = 7),  # Align facet labels horizontally
        strip.placement = "outside")+
  geom_text(data = filter(dot_plot_data, p_value < 0.05), 
            aes(label = "*"), nudge_y = -0.1,
            size = 5) 

dot_plot
```
