---
title: "Brier_Score_C-Index"
output: html_document
date: "2025-05-20"
---

```{r, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning=FALSE,
                      message=FALSE,
                      include=FALSE, 
                      tidy.opts=list(width.cutoff=60),tidy=TRUE)
#echo=FALSE, will not display the code in the code chunk 
#warning = FALSE, no warning messages 
#message = FALSE, no messages generated by code
#include = FALSE, will run chunk but not display it
options(scipen = 999)
```

```{r, echo =FALSE, message = FALSE}
packages <- c("dplyr", "ggplot2", "lubridate", "DBI", "vaultr", "skimr", "haven", "janitor", 
              "readr", "stringr", "modeest", "here", "kableExtra", "flextable", "stringi", 
              "tidyr", "stats", "fANCOVA", "forecast", "xts", "growthcleanr", "readxl", 
              "survival", "survminer", "cmprsk", "gtsummary", "officer", 
              "broom", "pec", "riskRegression", "data.table", "pROC")
lapply(packages, library, character.only = TRUE)

```

```{r input_data}
overall_data <- readRDS("/bd-fs-mnt/TenantShare/exthome/home/l578311/cvd/pgs_revised/data/final_cohorts/pgs_zscores_overall_peter.rds")

afr_data <- overall_data %>% filter(ancestry == "AFR")
amr_data <- overall_data %>% filter(ancestry == "AMR")
eur_data <- overall_data %>% filter(ancestry == "EUR")
eas_data <- overall_data %>% filter(ancestry == "EAS")
```


```{r}


#outcome variables
outcomes <- c("inc_anycmd",  
              "inc_hyperten",  
              "inc_diabetes",  
              "inc_dyslipid",  
              "inc_anycvd",  
              "inc_seriouscvd",  
              "inc_arrhythmia",  
              "inc_hf", 
              "inc_ischemic",  
              "inc_stroke",  
              "inc_vte",  
              "inc_cvddeath")

#PGS scores
pgs<- c("z_pgs_angina", "z_pgs_apolipoprotein_a", "z_pgs_apolipoprotein_b",
              "z_pgs_atrial_fibrillation", "z_pgs_body_fat_percentage", 
              "z_pgs_body_mass_index_adult", "z_pgs_body_mass_index_early_life", 
              "z_pgs_body_weight", "z_pgs_c_reactive_protein", 
              "z_pgs_cad2", "z_pgs_cad3", "z_pgs_cad3725", 
              "z_pgs_coronary_heart_disease", 
              "z_pgs_diabetes", "z_pgs_diastolic_blood_pressure", 
              "z_pgs_fasting_glucose", "z_pgs_fasting_glucose_adjusted_for_bmi", 
              "z_pgs_hb_a1c", "z_pgs_hdl_cholesterol", "z_pgs_heart_failure", 
              "z_pgs_hypertension", "z_pgs_ischaemic_stroke", 
              "z_pgs_ldl_cholesterol", "z_pgs_lipoprotein_a",
              "z_pgs_myocardial_infarction", "z_pgs_non_fasting_glucose", 
              "z_pgs_sbp", "z_pgs_systolic_blood_pressure", 
              "z_pgs_total_cholesterol", "z_pgs_triglyceride", 
              "z_pgs_type_2_diabetes", "z_pgs_waist_circumference")

#outcome strings
outcome_strings  <- c("Any CMD risk factor", 
                      "Hypertension", 
                      "Diabetes", 
                      "Dyslipidemia", 
                      "Any CVD", 
                      "Serious CVD", 
                      "Arrhythmia", 
                      "Heart failure or cardiomyopathy",
                      "Ischemic heart disease", 
                      "Stroke", 
                      "VTE", 
                      "CVD-related death")

label_outcomes <- data.table(
  outcome = outcomes,
  outcome_string = outcome_strings
)
```

# Brier Score C-index WITH Covariates

## Overall
```{r}
data_obj <- overall_data
outcomes_list <- unique(outcomes)
pgs_list <- unique(pgs)

results <- data.table()
for (outcome_i in outcomes_list) {
  print(outcome_i)
  prev_cov <- if (outcome_i %in% c("inc_anycmd", "inc_hyperten", "inc_diabetes", "inc_dyslipid")) {
    "prev_anycvd"
  } else {
    "prev_anycmd"
  }
  data_obj1 <-data_obj %>% 
    filter(!!sym(outcome_i) %in% c(0,1)) %>% 
    filter(smoke_status_6m != "Unknown") %>%
    filter(bl_educlvl_5cat != "Unknown")
  data_obj1 <- data_obj1 %>%
    mutate(!!sym(outcome_i) := as.numeric(!!sym(outcome_i))-1)
  
  data_obj1$smoke_status_6m <- factor(data_obj1$smoke_status_6m)
  levels(data_obj1$smoke_status_6m)
  data_obj1$bl_educlvl_5cat <- factor(data_obj1$bl_educlvl_5cat)
  levels(data_obj1$bl_educlvl_5cat)
  
  time_var <- paste0(outcome_i, "_time")
  
  for (pgs_var in pgs_list){
    print(pgs_var)
    
    temp_data <- data.table()
    covariates <- c(pgs_var, "dxage", "bl_inc_cat2", "bl_educlvl_5cat", "bmi_new","bl_meno_status", "smoke_status_6m", "pc_util_count", prev_cov, "rad_tx_yn", "anthra_yn", "tras_yn", "horm_yn")
   formula_str <- paste0("Surv(", paste(time_var), "," , outcome_i, ") ~ ", paste(covariates, collapse = " + ")) 
   adj_model <- coxph(formula =  as.formula(formula_str), data = data_obj1, x = TRUE, y = TRUE)
   c_index <- concordance(adj_model)$concordance
   
   times_to_predict <- median(data_obj1[[time_var]])

    # Calculate C-index using pec()
   formula_str_2 <- paste0("Surv(", time_var, ", ", outcome_i, ") ~1")
   formula_2 <- as.formula(formula_str_2)
   pec_result <- pec(
      object = list("CoxPH" = adj_model),
      formula = formula_2,
      data = data_obj1,
      exact = TRUE,
      splitMethod = "none",
      cens.model = "cox",
      times= times_to_predict
    )
   n_obs <- length(pec_result$AppErr$CoxPH)
   event_half_estimate <- round(n_obs/2)
   brier <- pec_result$AppErr$CoxPH[event_half_estimate]
   
   # Pyll AUC
   predicted_risk <- predictRisk(adj_model, newdata = data_obj1, times = times_to_predict)
   binary_outcomes <- ifelse(data_obj1[[sym(time_var)]] <= times_to_predict & data_obj1[[sym(outcome_i)]] == 1, 1,0)
   roc_obj <- roc(binary_outcomes ~ predicted_risk)
   
   auc <- auc(roc_obj)[1]
   auc_lower <- ci(roc_obj)[1]
   auc_upper <- ci(roc_obj)[3] 
   
   temp_data <- data.table(
        term = pgs_var,
        outcome = outcome_i,
        c_index = c_index,
        brier_50 = brier,
        auc = auc,
        auc_ci_lower = auc_lower,
        auc_ci_upper = auc_upper
   )
   results <- bind_rows(results, temp_data)
   
  }
}
results <- left_join(results, label_outcomes, by = "outcome")
results$ancestry<-"ALL"
overall_cindex_results <- results

#adj_model<- coxph(Surv(inc_anycmd_time, inc_anycmd) ~ 
 #                   z_pgs_angina + dxage + bl_inc_cat2 + bl_educlvl_5cat + bmi_new + bl_meno_status + smoke_status_6m + pc_util_count + prev_anycvd + #rad_tx_yn + anthra_yn + tras_yn + horm_yn, data = data_obj1, x = TRUE, y = TRUE)
#c_index <- concordance(adj_model)$concordance

```

## AFR

```{r, warning = FALSE}
ancestries <- c("AFR", "AMR", "EUR", "EAS")
for (anc in ancestries){
  print(anc)
  data_obj <- overall_data %>% filter(ancestry == anc)
  outcomes_list <- unique(outcomes)
  pgs_list <- unique(pgs)
  
  results<- data.table()
  for (outcome_i in outcomes_list) {
    print(outcome_i)
    prev_cov <- if (outcome_i %in% c("inc_anycmd", "inc_hyperten", "inc_diabetes", "inc_dyslipid")) {
      "prev_anycvd"
    } else {
      "prev_anycmd"
    }
    if(anc =="AMR"){
        data_obj1 <-data_obj %>% 
                filter(!!sym(outcome_i) %in% c(0,1)) %>% 
                filter(smoke_status_6m != "Unknown") %>%
                filter(bl_educlvl_5cat != "Unknown") %>% filter(smoke_status_6m != "Current")
        
        data_obj1 <- data_obj1 %>%
                mutate(!!sym(outcome_i) := as.numeric(!!sym(outcome_i))-1)
        
        data_obj1$smoke_status_6m <- factor(data_obj1$smoke_status_6m)
        data_obj1$bl_educlvl_5cat <- factor(data_obj1$bl_educlvl_5cat)
    } else{
          data_obj1 <-data_obj %>% 
            filter(!!sym(outcome_i) %in% c(0,1)) %>% 
            filter(smoke_status_6m != "Unknown") %>%
            filter(bl_educlvl_5cat != "Unknown")
          data_obj1 <- data_obj1 %>%
            mutate(!!sym(outcome_i) := as.numeric(!!sym(outcome_i))-1)
          
          data_obj1$smoke_status_6m <- factor(data_obj1$smoke_status_6m)
          data_obj1$bl_educlvl_5cat <- factor(data_obj1$bl_educlvl_5cat)
    }
    time_var <- paste0(outcome_i, "_time")
    
    for (pgs_var in pgs_list){
      print(pgs_var)
      
      temp_data <- data.table()
      covariates <- c(pgs_var, "dxage", "bl_inc_cat2", "bl_educlvl_5cat", "bmi_new","bl_meno_status", "smoke_status_6m", "pc_util_count", prev_cov, "rad_tx_yn", "anthra_yn", "tras_yn", "horm_yn")
     formula_str <- paste0("Surv(", paste(time_var), "," , outcome_i, ") ~ ", paste(covariates, collapse = " + ")) 
     adj_model <- coxph(formula =  as.formula(formula_str), data = data_obj1, x = TRUE, y = TRUE)
     c_index <- concordance(adj_model)$concordance
     
     times_to_predict <- median(data_obj1[[time_var]])
  
      # Calculate C-index using pec()
     formula_str_2 <- paste0("Surv(", time_var, ", ", outcome_i, ") ~1")
     formula_2 <- as.formula(formula_str_2)
     pec_result <- pec(
        object = list("CoxPH" = adj_model),
        formula = formula_2,
        data = data_obj1,
        exact = TRUE,
        splitMethod = "none",
        cens.model = "cox",
        times= times_to_predict
      )
     n_obs <- length(pec_result$AppErr$CoxPH)
     event_half_estimate <- round(n_obs/2)
     brier <- pec_result$AppErr$CoxPH[event_half_estimate]
     
     temp_data <- data.table(
          term = pgs_var,
          outcome = outcome_i,
          c_index = c_index,
          brier_50 = brier
     )
  
     results <- bind_rows(results, temp_data)
    }
  }
  results$ancestry <- anc
  results <- left_join(results, label_outcomes, by = "outcome")
  fwrite(results, paste0(anc, "_metrics_with_covar_cox_ph.txt"), sep = "\t", quote = F, row.names = F, col.names = T)
}




```


# PGS No Covariates

## AFR
```{r all_anc_no_vocar}
ancestries <- c("AFR", "AMR", "EUR", "EAS")
for (anc in ancestries){
  data_obj <- overall_data %>% filter(ancestry == anc)
  outcomes_list <- unique(outcomes)
  pgs_list <- unique(pgs)
  
  results_pgs_only <- data.table()
  for (outcome_i in outcomes_list) {
    
    data_obj1 <- data_obj %>% filter(!!sym(outcome_i) %in% c(0,1)) 
    data_obj1 <- data_obj1 %>%
      mutate(!!sym(outcome_i) := as.numeric(!!sym(outcome_i)) -1)
  
    
    time_var <- paste0(outcome_i, "_time")
    
    for (pgs_var in pgs_list){
      print(pgs_var)
      
     temp_data <- data.table()
     formula_str <- paste0("Surv(", paste(time_var), "," , outcome_i, ") ~ ", paste(pgs_var)) 
     adj_model <- coxph(formula =  as.formula(formula_str), data = data_obj1, x = TRUE, y = TRUE)
     c_index <- concordance(adj_model)$concordance
     
     times_to_predict <-  median(data_obj1[[time_var]])
  
      # Calculate C-index using pec()
     formula_str_2 <- paste0("Surv(", time_var, ", ", outcome_i, ") ~1")
     formula_2 <- as.formula(formula_str_2)
     pec_result <- pec(
        object = list("CoxPH" = adj_model),
        formula = formula_2,
        data = data_obj1,
        exact = TRUE,
        splitMethod = "none",
        cens.model = "cox",
        times= times_to_predict
      )
     n_obs <- length(pec_result$AppErr$CoxPH)
     event_half_estimate <- round(n_obs/2)
     brier <- pec_result$AppErr$CoxPH[event_half_estimate]
     
     # Pyll AUC
     predicted_risk <- predictRisk(adj_model, newdata = data_obj1, times = times_to_predict)
     binary_outcomes <- ifelse(data_obj1[[sym(time_var)]] <= times_to_predict & data_obj1[[sym(outcome_i)]] == 1, 1,0)
     roc_obj <- roc(binary_outcomes ~ predicted_risk)
     
     auc <- auc(roc_obj)[1]
     auc_lower <- ci(roc_obj)[1]
     auc_upper <- ci(roc_obj)[3] 
     
     temp_data <- data.table(
          term = pgs_var,
          outcome = outcome_i,
          c_index = c_index,
          brier_50 = brier,
          auc = auc,
          auc_ci_lower = auc_lower,
          auc_ci_upper = auc_upper
     )
  
     results_pgs_only <- bind_rows(results_pgs_only, temp_data)
    }
  }
  results_pgs_only$ancestry <- anc
  results_pgs_only <- left_join(results_pgs_only, label_outcomes, by = "outcome")
  fwrite(results_pgs_only, paste0(anc, "_metrics_cox_ph.txt"), sep = "\t", quote = F, row.names = F, col.names = T)
}

```


## Overall

```{r overal_no_voar}
data_obj <- overall_data
outcomes_list <- unique(outcomes)
pgs_list <- unique(pgs)

results_pgs_only <- data.table()
for (outcome_i in outcomes_list) {
  
  data_obj1 <- data_obj %>% filter(!!sym(outcome_i) %in% c(0,1)) 
  data_obj1 <- data_obj1 %>%
    mutate(!!sym(outcome_i) := as.numeric(!!sym(outcome_i)) -1)

  
  time_var <- paste0(outcome_i, "_time")
  
  for (pgs_var in pgs_list){
    print(pgs_var)
    
   temp_data <- data.table()
   formula_str <- paste0("Surv(", paste(time_var), "," , outcome_i, ") ~ ", paste(pgs_var)) 
   adj_model <- coxph(formula =  as.formula(formula_str), data = data_obj1, x = TRUE, y = TRUE)
   c_index <- concordance(adj_model)$concordance
   
   times_to_predict <- median(data_obj1[[time_var]])

    # Calculate C-index using pec()
   formula_str_2 <- paste0("Surv(", time_var, ", ", outcome_i, ") ~1")
   formula_2 <- as.formula(formula_str_2)
   pec_result <- pec(
      object = list("CoxPH" = adj_model),
      formula = formula_2,
      data = data_obj1,
      exact = TRUE,
      splitMethod = "none",
      cens.model = "cox",
      times= times_to_predict
    )
   n_obs <- length(pec_result$AppErr$CoxPH)
   event_half_estimate <- round(n_obs/2)
   brier <- pec_result$AppErr$CoxPH[event_half_estimate]
   
   predicted_risk <- predictRisk(adj_model, newdata = data_obj1, times = times_to_predict)
   binary_outcomes <- ifelse(data_obj1[[sym(time_var)]] <= times_to_predict & data_obj1[[sym(outcome_i)]] == 1, 1,0)
   roc_obj <- roc(binary_outcomes ~ predicted_risk)
     
   auc <- auc(roc_obj)[1]
   auc_lower <- ci(roc_obj)[1]
   auc_upper <- ci(roc_obj)[3] 
   
   temp_data <- data.table(
          term = pgs_var,
          outcome = outcome_i,
          c_index = c_index,
          brier_50 = brier,
          auc = auc,
          auc_ci_lower = auc_lower,
          auc_ci_upper = auc_upper
     )

   results_pgs_only <- bind_rows(results_pgs_only, temp_data)
  }
}

results_pgs_only$ancestry <- "ALL"
results_pgs_only <-left_join(results_pgs_only, label_outcomes, by = "outcome")
overall_results_pgs <- results_pgs_only

fwrite(overall_results_pgs, "Overall_metrics_cox_ph.txt")
````
