---
title: "005_km_curves_results_20240416"
author: "Alexa Zimbalist"
date: "April 16, 2024"
output:
  word_document: default
  output: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning=FALSE,
                      message=FALSE,
                      include=FALSE, 
                      tidy.opts=list(width.cutoff=60),tidy=TRUE)
#echo=FALSE, will not display the code in the code chunk 
#warning = FALSE, no warning messages 
#message = FALSE, no messages generated by code
#include = FALSE, will run chunk but not display it

options(scipen=999)
#get rid of scientific notation
```

```{r program steps}
#The goal of this program is to create kaplan-meier curves for Song Yao's CVD PGS analysis. 
#Outcomes: Any CMD, Hypertension, Diabetes, Dyslipidemia, Any CVD, Serious CVD, Arrhythmia, Ischemic Heart Disease
#Exposures: Standardized PGS scores for angina, apolipoprotein B, atrial fibrillation,, cad3725, diastolic blood pressure, fasting glucose adjusted for BMI, HbA1C, hypertension, LDL cholesterol, systolic blood pressure, total cholesterol, triglyceride, type 2 diabetes. All standardized PGS scores should be categorized into tertiles based on the values within each racial/ethnic group. 
#Race: White

#Program Steps: 
# (1) Import clean cohort
# (2) Modify cohort: 
#       - For this figure, competing risk of all-cause mortality should be treated as 0's 
#         (not having the incident event and censored when they die)
#       - Convert survival time to months
#       - For this figure, remove those who had prevalent conditions
#       - Create tertiles for standardized PGS scores
# (3) Create survival plots and save
```

```{r install packages and libraries, include=F}
packages <- c("dplyr", "ggplot2", "lubridate", "DBI", "vaultr", "skimr", "haven", "janitor", 
              "readr", "stringr", "modeest", "here", "kableExtra", "flextable", "stringi", 
              "tidyr", "stats", "fANCOVA", "forecast", "xts", "growthcleanr", "readxl", 
              "survival", "survminer", "cmprsk", "gtsummary", "officer", 
              "sjlabelled")
lapply(packages, library, character.only = TRUE)
```

```{r establishing connection}
#create object for vault connection:
options(connectionObserver = NULL)
vault <- vaultr::vault_client(login=TRUE)

#create objects for DSN name and secret path string:
databaseDSN <- "ACIDSN_DORRDB"
secretPath <- paste("dorkv",Sys.info()['user'],"dbconnection",databaseDSN,sep="/")

#create connection object (changing options so that odbc isn't loading all the tables)
options(connectionObserver = NULL) 
con_rdb <- dbConnect(odbc::odbc(),
                  dsn = databaseDSN,
                  UID    = vault$read(secretPath, field="userid"),
                  PWD    = vault$read(secretPath, field="password"))
```

```{r check where working directory is}
here()
```

```{r import clean datasets, eval = FALSE}
setwd("/bd-fs-mnt/TenantShare/exthome/home/l578311/cvd/")
#import full cohort PGS zscores
zscores_overall <- read_rds(here("cvd",
                                 "pgs_revised",
                                 "data",
                                 "final_cohorts",
                                 "pgs_zscores_overall_peter.rds"))

#import african ancestry PGS zscores
zscores_afr <- read_rds(here("cvd", "pgs_revised",
                             "data",
                             "final_cohorts",
                             "pgs_zscores_afr_peter.rds"))

#import admixed american ancestry PGS zscores
zscores_amr <- read_rds(here("cvd",
                             "pgs_revised",
                             "data",
                             "final_cohorts",
                             "pgs_zscores_amr_peter.rds"))

#import east asian ancestry PGS zscores
zscores_eas <- read_rds(here("cvd",
                             "pgs_revised",
                             "data",
                             "final_cohorts",
                             "pgs_zscores_eas_peter.rds"))

#import european ancestry PGS zscores
zscores_eur <- read_rds(here("cvd",
                             "pgs_revised",
                             "data",
                             "final_cohorts",
                             "pgs_zscores_eur_peter.rds"))
```

```{r}
zscores_overall <- readRDS("/bd-fs-mnt/TenantShare/exthome/home/l578311/cvd/pgs_revised/data/final_cohorts/pgs_zscores_overall_peter.rds")
cohort_white <- zscores_overall %>% filter(ancestry=="EUR")
```


```{r keep variables for kaplan meier curves}
#keep variables for kaplan meier curves
cohort_white2 <- cohort_white %>% select(studyid, race, 
                                         inc_anycmd, inc_anycmd_time, prev_anycmd, 
                                         inc_anycvd, inc_anycvd_time, prev_anycvd, 
                                         inc_arrhythmia, inc_arrhythmia_time, prev_arrhythmia, 
                                         inc_diabetes, inc_diabetes_time, prev_diabetes, 
                                         inc_dyslipid, inc_dyslipid_time, prev_dyslipid, 
                                         inc_hyperten, inc_hyperten_time, prev_hyperten, 
                                         inc_ischemic, inc_ischemic_time, prev_ischemic, 
                                         inc_seriouscvd, inc_seriouscvd_time, prev_seriouscvd, 
                                         z_pgs_angina, z_pgs_apolipoprotein_b, z_pgs_atrial_fibrillation, 
                                         z_pgs_cad3725, z_pgs_diastolic_blood_pressure,
                                         z_pgs_fasting_glucose_adjusted_for_bmi, 
                                         z_pgs_hb_a1c, z_pgs_hypertension, z_pgs_ldl_cholesterol, 
                                         z_pgs_systolic_blood_pressure, z_pgs_total_cholesterol, 
                                         z_pgs_triglyceride, z_pgs_type_2_diabetes) 

#for this figure, competing risk of all-cause mortality should be treated as 0's (not having the incident event and censored when they die)
#convert time to months
cohort_white3 <- cohort_white2 %>% mutate_at(vars(inc_anycmd, inc_anycvd, inc_arrhythmia, 
                                                  inc_diabetes, inc_dyslipid, inc_hyperten, 
                                                  inc_ischemic, inc_seriouscvd), 
                                             ~case_when(.==0 ~ as.numeric(0), 
                                                        .==1 ~ as.numeric(1),
                                                        .==2 ~ as.numeric(0), 
                                                        .==3 ~ as.numeric(3))) %>%
                                    mutate_at(vars(inc_anycmd_time, inc_anycvd_time, inc_arrhythmia_time, 
                                                  inc_diabetes_time, inc_dyslipid_time, inc_hyperten_time, 
                                                  inc_ischemic_time, inc_seriouscvd_time), 
                                              ~round(./30.417, 2))


#check work 
cohort_white2 %>% tabyl(inc_seriouscvd)
cohort_white3 %>% tabyl(inc_seriouscvd)
```

```{r remove those with prevalent conditions}
#create function that removes those with prevalent conditions for each outcome
remove_prev = function(out_var) {
  
  #create new dataframe for each outcome
  df_outcome <- cohort_white3 %>% filter(!!as.symbol(out_var) != 3)
  
  #save new dataset as an object in the Global Environment
  assign(paste0(out_var), df_outcome, envir = .GlobalEnv)
}

#create list of arguments 
remove_prev_args = list(c("inc_anycmd", "inc_anycvd", "inc_arrhythmia", 
                          "inc_diabetes", "inc_dyslipid", "inc_hyperten", 
                          "inc_ischemic", "inc_seriouscvd"))

#apply function 
purrr::pmap(remove_prev_args, remove_prev)

#check work 
# cohort_white3 %>% filter(inc_anycvd!=3)
# inc_anycvd %>% tabyl(inc_anycvd)
# cohort_white3 %>% tabyl(inc_anycvd)
```

```{r create pgs tertiles within race}
#write function that creates tertiles for the pgs scores within race/ethnicity==White
tertiles = function(df_name, out_string) {
   #create new dataframe for each outcome
   df_out_new <- df_name %>% mutate(z_pgs_angina_tert = ntile(z_pgs_angina, 3),
                                    z_pgs_apolipoprotein_b_tert = ntile(z_pgs_apolipoprotein_b, 3),
                                    z_pgs_atrial_fibrillation_tert = ntile(z_pgs_atrial_fibrillation, 3),
                                    z_pgs_cad3725_tert = ntile(z_pgs_cad3725, 3),
                                    z_pgs_diastolic_blood_pressure_tert = 
                                      ntile(z_pgs_diastolic_blood_pressure, 3),
                                    z_pgs_fasting_glucose_adjusted_for_bmi_tert = 
                                      ntile(z_pgs_fasting_glucose_adjusted_for_bmi, 3),
                                    z_pgs_hb_a1c_tert = ntile(z_pgs_hb_a1c, 3),
                                    z_pgs_hypertension_tert = ntile(z_pgs_hypertension, 3),
                                    z_pgs_ldl_cholesterol_tert = ntile(z_pgs_ldl_cholesterol, 3),
                                    z_pgs_systolic_blood_pressure_tert = ntile(z_pgs_systolic_blood_pressure, 3),
                                    z_pgs_total_cholesterol_tert = ntile(z_pgs_total_cholesterol, 3),
                                    z_pgs_triglyceride_tert = ntile(z_pgs_triglyceride, 3),
                                    z_pgs_type_2_diabetes_tert = ntile(z_pgs_type_2_diabetes, 3)) %>% 
                              mutate_at(vars(z_pgs_angina_tert, z_pgs_apolipoprotein_b_tert, 
                                             z_pgs_atrial_fibrillation_tert, z_pgs_cad3725_tert, 
                                             z_pgs_diastolic_blood_pressure_tert,
                                             z_pgs_fasting_glucose_adjusted_for_bmi_tert, 
                                             z_pgs_hb_a1c_tert, z_pgs_hypertension_tert, 
                                             z_pgs_ldl_cholesterol_tert, 
                                             z_pgs_systolic_blood_pressure_tert, 
                                             z_pgs_total_cholesterol_tert, 
                                             z_pgs_triglyceride_tert, z_pgs_type_2_diabetes_tert), 
                                         ~case_when(.==1 ~ as.factor("Low"), 
                                                    .==2 ~ as.factor("Medium"),
                                                    .==3 ~ as.factor("High")))
                     
  #save new dataset as an object in the Global Environment
  assign(paste0("tert_", out_string), df_out_new, envir = .GlobalEnv) 
  }

#create list of arguments 
tertiles_args = list(list(inc_anycmd, inc_anycvd, inc_arrhythmia, 
                          inc_diabetes, inc_dyslipid, inc_hyperten, 
                          inc_ischemic, inc_seriouscvd), 
                     c("inc_anycmd", "inc_anycvd", "inc_arrhythmia", 
                       "inc_diabetes", "inc_dyslipid", "inc_hyperten", 
                       "inc_ischemic", "inc_seriouscvd"))

#apply function 
purrr::pmap(tertiles_args, tertiles)

#check work
#***IMPORTANT NOTE: The tertiles will be different depending on the outcome!
# tert1 = quantile(inc_anycmd$z_pgs_angina, c(0:3/3))
# tert2 = quantile(inc_anycvd$z_pgs_angina, c(0:3/3))
# #-3.455, -0.477, 0.352, 3.25
# inc_anycmd %>% mutate(z_pgs_angina_tert = ntile(z_pgs_angina, 3)) %>%
#                select(studyid, z_pgs_angina, z_pgs_angina_tert) %>%
#                arrange(z_pgs_angina)
```

```{r create function for survival curves}
#create custom theme for Kaplan Meier curves
custom_theme1 <- function() {
  theme_survminer() %+replace%
    theme(plot.title=element_text(hjust=0.5)) 
}

#create custom theme for risk table
custom_theme2 <- function() {
  theme_survminer() %+replace%
    theme(plot.title=element_text(hjust=0.5), 
          axis.text.y = element_blank(), 
          axis.ticks.y = element_blank(), 
          axis.title.y = element_blank())
}

#create function for survival curves
survival_curves = function(out_time, out_var, pgs_var, df_name, 
                           pgs_var_string, out_var_string) {
  
  #compute survival curve
  fit <- surv_fit(as.formula(paste0("Surv(", out_time, ",", out_var, ") ~", pgs_var)), 
                  data=df_name)

  #create dataframe of survival curve components 
  fit_df <- data.frame(time = fit$time,
                       n.risk = fit$n.risk,
                       n.event = fit$n.event,
                       n.censor = fit$n.censor,
                       surv = fit$surv,
                       upper = fit$upper,
                       lower = fit$lower)

  #visualize survival curve
  curve <- ggsurvplot(fit, 
                      size = 1,  
                      break.time.by = 24, 
                      xlim = c(0, 144),
                      ylim = c(0, 0.05 + max(1 - fit$surv[fit$time <= 148])),
                      pval = TRUE, # Add p-value
                      pval.coord = c(0, 0.05 + max(1 - fit$surv[fit$time <= 148])),
                      censor = F,
                      tables.col = "strata",
                      risk.table = F,
                      fun = "event",
                      legend = "bottom", 
                      legend.title = element_blank(),
                      legend.labs = c("Low", "Medium", "High"),
                      xlab = "Time (Months)",
                      ylab = "Cumulative event probability", 
                      title = paste0(out_var_string, ": ", pgs_var_string),
                      palette = c("#4DBBD5FF", "#E64B35FF", "#00A087FF"), 
                      ggtheme = custom_theme1(), 
                      tables.theme = custom_theme2())
} 
```

```{r create survival curves}
#create lists of outcome time variables
out_time_vars_cmd <- c("inc_anycmd_time", "inc_anycmd_time", 
                       "inc_dyslipid_time", "inc_hyperten_time",
                       "inc_anycmd_time", "inc_diabetes_time", 
                       "inc_dyslipid_time", "inc_hyperten_time", 
                       "inc_anycmd_time", "inc_diabetes_time",
                       "inc_dyslipid_time", "inc_hyperten_time", 
                       "inc_anycmd_time", "inc_dyslipid_time", 
                       "inc_dyslipid_time")

out_time_vars_cvd <- c("inc_anycvd_time", "inc_arrhythmia_time", 
                       "inc_seriouscvd_time", "inc_ischemic_time")

#create lists of outcome variables
out_vars_cmd <- c("inc_anycmd", "inc_anycmd", 
                  "inc_dyslipid", "inc_hyperten",
                  "inc_anycmd", "inc_diabetes", 
                  "inc_dyslipid", "inc_hyperten", 
                  "inc_anycmd", "inc_diabetes",
                  "inc_dyslipid", "inc_hyperten", 
                  "inc_anycmd", "inc_dyslipid", 
                  "inc_dyslipid")

out_vars_cvd <- c("inc_anycvd", "inc_arrhythmia", 
                  "inc_seriouscvd", "inc_ischemic")

#create lists of outcome string variables
out_vars_string_cmd <- c("Any CMD", "Any CMD", 
                         "Dyslipidemia", "Hypertension", 
                         "Any CMD", "Diabetes", 
                         "Dyslipidemia", "Hypertension",
                         "Any CMD", "Diabetes", 
                         "Dyslipidemia", "Hypertension",
                         "Any CMD", "Dyslipidemia",
                         "Dyslipidemia")

out_vars_string_cvd <- c("Any CVD", "Arrhythmia",
                         "Serious CVD", 
                         "Ischemic Heart Disease")

#create lists of pgs variables 
pgs_vars_cmd <- c("z_pgs_apolipoprotein_b_tert", "z_pgs_total_cholesterol_tert", 
                  "z_pgs_apolipoprotein_b_tert", "z_pgs_diastolic_blood_pressure_tert", 
                  "z_pgs_fasting_glucose_adjusted_for_bmi_tert", "z_pgs_hb_a1c_tert", 
                  "z_pgs_ldl_cholesterol_tert", "z_pgs_hypertension_tert", 
                  "z_pgs_ldl_cholesterol_tert", "z_pgs_type_2_diabetes_tert", 
                  "z_pgs_total_cholesterol_tert", "z_pgs_systolic_blood_pressure_tert", 
                  "z_pgs_systolic_blood_pressure_tert", "z_pgs_angina_tert",
                  "z_pgs_triglyceride_tert")

pgs_vars_cvd <- c("z_pgs_atrial_fibrillation_tert", 
                  "z_pgs_atrial_fibrillation_tert", 
                  "z_pgs_atrial_fibrillation_tert", 
                  "z_pgs_cad3725_tert")

#create lists of pgs string variables
pgs_vars_string_cmd <- c("Apolipoprotein B", "Total Cholesterol", 
                         "Apolipoprotein B", "Diastolic Blood Pressure",
                         "Fasting Glucose Adjusted for BMI", "HbA1c",
                         "LDL Cholesterol", "Hypertension", 
                         "LDL Cholesterol", "Type 2 Diabetes", 
                         "Total Cholesterol", "Systolic Blood Pressure", 
                         "Systolic Blood Pressure", "Angina", 
                         "Triglycerides")

pgs_vars_string_cvd <- c("Atrial Fibrillation", "Atrial Fibrillation", 
                         "Atrial Fibrillation", "CAD")

#create list of arguments 
args_cmd = list(c(out_time_vars_cmd), 
                c(out_vars_cmd), 
                c(pgs_vars_cmd), 
               c(rep(list(tert_inc_anycmd), 2),
                 list(tert_inc_dyslipid),
                 list(tert_inc_hyperten), 
                 list(tert_inc_anycmd), 
                 list(tert_inc_diabetes),
                 list(tert_inc_dyslipid),
                 list(tert_inc_hyperten),
                 list(tert_inc_anycmd), 
                 list(tert_inc_diabetes),
                 list(tert_inc_dyslipid),
                 list(tert_inc_hyperten),
                 list(tert_inc_anycmd),
                 rep(list(tert_inc_dyslipid), 2)), 
                c(pgs_vars_string_cmd), 
                c(out_vars_string_cmd))

args_cvd = list(c(out_time_vars_cvd), 
                c(out_vars_cvd), 
                c(pgs_vars_cvd), 
                list(tert_inc_anycvd, tert_inc_arrhythmia, 
                     tert_inc_ischemic, tert_inc_seriouscvd), 
                c(pgs_vars_string_cvd), 
                c(out_vars_string_cvd))

#apply function to create survival curves and save as lists
surv_plots_cmd <- purrr::pmap(args_cmd, survival_curves)
surv_plots_cvd <- purrr::pmap(args_cvd, survival_curves)

```

```{r check work}
surv_plots_cmd2 <- surv_plots_cmd[-c(5,15)]
surv_plots_cvd

#check work 
# fit_test <- surv_fit(Surv(inc_dyslipid_time, inc_dyslipid) ~ z_pgs_angina_tert, 
#                      data=tert_inc_dyslipid)
# ggsurvplot(fit_test, size = 1, break.time.by = 24, 
#            xlim = c(0, 144),
#            ylim = c(0, 0.05 + max(1 - fit_test$surv[fit_test$time <= 148])),
#            pval = TRUE, # Add p-value
#            pval.coord = c(0, 0.05 + max(1 - fit_test$surv[fit_test$time <= 148])),
#            censor = F, tables.col = "strata",
#            risk.table = F, fun = "event", legend = "bottom", 
#            legend.title = element_blank(), legend.labs = c("Low", "Medium", "High"),
#            xlab = "Time (Months)", ylab = "Cumulative event probability", 
#            palette = c("#4DBBD5FF", "#E64B35FF", "#00A087FF"))

```

```{r save survival curves}
#save CMD survival curves
 png(here("pgs", "output", "km_curves_results_cmd.png"), 
     width = 1800, height = 1800, res = 110)
 arrange_ggsurvplots(surv_plots_cmd2, ncol = 4, nrow = 4)
 dev.off()
 
 #save CVD survival curves
 png(here("pgs", "output", "km_curves_results_cvd.png"),
     width = 450, height = 1800, res = 110)
 arrange_ggsurvplots(surv_plots_cvd, ncol = 1, nrow = 4)
 dev.off()

```


